#!/usr/bin/env python3
"""
Find and remove false per-ligand .done flags where weighted_scores.csv count
is below the expected anchor residue count.

Also removes the batch-level rosetta_round1.done if the batch's total CSV
count does not match the expected count (ligands x expected per-ligand CSVs),
or if any ligand in that batch had a false .done flag, so Snakemake will
re-process the batch on the next run.

Additionally removes leftover Rosetta chunk scripts (ros1_chunk_*.py /
ros1_*.py) left behind in each processed batch's round1/ directory, so stale
scripts from dead monitor jobs don't linger.

Batches are scanned concurrently (16 folders at a time by default) since the
checks are I/O-bound on NFS.

Usage:
  python utils/clean_false_done_flags.py --dry-run              # count only
  python utils/clean_false_done_flags.py --delete               # actually remove
  python utils/clean_false_done_flags.py --delete --workers 32  # more concurrency
"""

import os
import sys
import argparse
import glob
import concurrent.futures

BASE_DIR = "/pi/summer.thyme-umw/Ji_rosetta_discovery"

# Both config_state3.yaml and config_state4.yaml have 10 anchor residues.
# If this changes, update accordingly.
EXPECTED_CSV_COUNT = 10

# Number of batch folders to scan concurrently.
DEFAULT_WORKERS = 16

# Leftover per-chunk Rosetta scripts generated by the rosetta_discovery_round1
# monitor shell (written as round1/ros1_chunk_<n>.py). Mirrors the rm patterns
# in workflows/step2_rosetta1.smk.
ROSETTA_PY_PATTERNS = ["ros1_chunk_*.py", "ros1_*.py"]


def clean_rosetta_python_files(round1_dir, dry_run=True):
    """Remove leftover Rosetta chunk scripts (*.py) from a round1/ directory.
    Returns (count_removed, log_lines)."""
    removed = 0
    lines = []
    seen = set()
    for pattern in ROSETTA_PY_PATTERNS:
        for py_file in glob.glob(os.path.join(round1_dir, pattern)):
            if py_file in seen:
                continue
            seen.add(py_file)
            removed += 1
            if dry_run:
                lines.append(f"  [WOULD REMOVE] {py_file}  (stale Rosetta python script)")
            else:
                try:
                    os.remove(py_file)
                    lines.append(f"  [REMOVED] {py_file}  (stale Rosetta python script)")
                except OSError as e:
                    lines.append(f"  [ERROR] {py_file}: {e}")
    return removed, lines


def process_batch(batch_dir, dry_run=True, expected=EXPECTED_CSV_COUNT):
    """Scan one batch folder. Returns
    (log_lines, lig_done_removed, batch_done_removed, py_removed, affected)."""
    lines = []
    round1_dir = os.path.join(batch_dir, "round1")
    if not os.path.isdir(round1_dir):
        return lines, 0, 0, 0, 0

    # Remove stale Rosetta chunk scripts left by finished/dead monitors.
    py_removed, py_lines = clean_rosetta_python_files(round1_dir, dry_run=dry_run)
    lines.extend(py_lines)

    batch_lig_removed = 0
    n_ligands = 0
    for entry in sorted(os.listdir(round1_dir)):
        lig_path = os.path.join(round1_dir, entry)
        if not os.path.isdir(lig_path):
            continue
        n_ligands += 1

        lig_done_file = os.path.join(round1_dir, f"{entry}.done")
        if not os.path.exists(lig_done_file):
            continue

        # Count weighted_scores.csv files under this ligand's anchor dirs
        csv_files = glob.glob(os.path.join(lig_path, "*", "weighted_scores.csv"))
        csv_count = len(csv_files)

        if csv_count < expected:
            batch_lig_removed += 1
            if dry_run:
                lines.append(f"  [WOULD REMOVE] {lig_done_file}  ({csv_count}/{expected} CSVs)")
            else:
                try:
                    os.remove(lig_done_file)
                    lines.append(f"  [REMOVED] {lig_done_file}  ({csv_count}/{expected} CSVs)")
                except OSError as e:
                    lines.append(f"  [ERROR] {lig_done_file}: {e}")

    # ── Batch-level check: the done flag is false if the total CSV count
    # does not match the expected count (n_ligands x expected), even when no
    # per-ligand .done files exist (e.g. batches stamped done without ever
    # running Rosetta).
    csv_total = len(glob.glob(os.path.join(round1_dir, "*", "*", "weighted_scores.csv")))
    expected_total = n_ligands * expected
    count_mismatch = n_ligands > 0 and csv_total < expected_total
    if count_mismatch:
        lines.append(f"  [BATCH] CSV count {csv_total} < expected {expected_total} ({n_ligands} ligands x {expected})")

    batch_done_removed = 0
    affected = 1 if (batch_lig_removed > 0 or count_mismatch) else 0
    if affected:
        batch_done_flag = os.path.join(batch_dir, "rosetta_round1.done")
        if count_mismatch:
            reason = f"CSV count {csv_total} < expected {expected_total} ({n_ligands} ligands x {expected})"
        else:
            reason = f"{batch_lig_removed} false ligand .done flags in batch"
        if dry_run:
            lines.append(f"  [WOULD REMOVE] {batch_done_flag}  ({reason})")
        else:
            try:
                os.remove(batch_done_flag)
                batch_done_removed = 1
                lines.append(f"  [REMOVED] {batch_done_flag}  ({reason})")
            except OSError as e:
                lines.append(f"  [ERROR] {batch_done_flag}: {e}")

    if lines:
        lines.append("")
    return lines, batch_lig_removed, batch_done_removed, py_removed, affected


def collect_batch_dirs():
    """Return batch dirs (with a rosetta_round1.done flag) across all states."""
    batch_dirs = []
    for state in ["snakemake_state3", "snakemake_state4"]:
        state_path = os.path.join(BASE_DIR, "output", state, "tmp")
        if not os.path.isdir(state_path):
            continue
        for batch_name in sorted(os.listdir(state_path)):
            batch_dir = os.path.join(state_path, batch_name)
            if not batch_name.startswith("batch_") or not os.path.isdir(batch_dir):
                continue
            if os.path.exists(os.path.join(batch_dir, "rosetta_round1.done")):
                batch_dirs.append(batch_dir)
    return batch_dirs


def clean_false_done_flags(dry_run=True, workers=DEFAULT_WORKERS):
    """Scan all done-flagged batches concurrently.
    Removes <ligand>.done files where CSVs < EXPECTED_CSV_COUNT; if any ligand
    in a batch was corrected, also removes rosetta_round1.done."""

    total_lig_done_removed = 0
    total_batch_done_removed = 0
    total_py_removed = 0
    batches_affected = 0

    batch_dirs = collect_batch_dirs()
    print(f"Scanning {len(batch_dirs):,} done-flagged batches with {workers} workers...\n")

    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {executor.submit(process_batch, bd, dry_run): bd for bd in batch_dirs}
        done = 0
        total = len(futures)
        for future in concurrent.futures.as_completed(futures):
            batch_dir = futures[future]
            try:
                lines, lig_removed, batch_removed, py_removed, affected = future.result()
            except Exception as e:
                print(f"[ERROR] {batch_dir}: {e}")
                continue
            for line in lines:
                print(line)
            total_lig_done_removed += lig_removed
            total_batch_done_removed += batch_removed
            total_py_removed += py_removed
            batches_affected += affected
            done += 1
            if done % 50 == 0 or done == total:
                print(f"[progress] {done}/{total} batches scanned")

    return (total_lig_done_removed, total_batch_done_removed,
            total_py_removed, batches_affected)


def main():
    parser = argparse.ArgumentParser(
        description="Clean up false .done flags (CSVs < expected anchor count)"
    )
    parser.add_argument("--dry-run", action="store_true", default=True,
                        help="Only report what would be removed (default)")
    parser.add_argument("--delete", action="store_true",
                        help="Actually delete the false done flags")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS,
                        help=f"Number of batch folders to scan concurrently (default {DEFAULT_WORKERS})")
    args = parser.parse_args()

    dry_run = not args.delete
    if args.delete:
        print("=== DELETING false done flags ===\n")
    else:
        print("=== DRY RUN: Finding false done flags ===\n")

    n_lig, n_batch, n_py, n_affected = clean_false_done_flags(
        dry_run=dry_run, workers=args.workers)

    print(f"{'='*60}")
    if dry_run:
        print(f"DRY RUN SUMMARY:")
        print(f"  False ligand .done flags:  {n_lig:,}")
        print(f"  Batches to re-run:         {n_batch:,} (of {n_affected:,} affected)")
        print(f"  Stale Rosetta py scripts:  {n_py:,}")
        print(f"\nRun with --delete to actually remove these flags.")
    else:
        print(f"REMOVAL SUMMARY:")
        print(f"  Ligand .done flags removed:  {n_lig:,}")
        print(f"  Batch rosetta_round1.done:   {n_batch:,}")
        print(f"  Stale Rosetta py scripts:    {n_py:,}")
        print(f"  Batches affected:            {n_affected:,}")


if __name__ == "__main__":
    main()
